### ISSUE TITLE
App crashes and restarts the Ledger device

### ISSUE THREAD

**Issue by bferenc** [ava-labs/ledger-avalanche#112]
We are using the [WebUSB transport](https://www.npmjs.com/package/@ledgerhq/hw-transport-webusb) in the Core extension for communicating with the Ledger device. We've recently noticed that if we send certain requests to the Avalanche app and close the transport before it can send back the response, the application will freeze for a few seconds and the device will restart afterwards. We found 2 problematic requests / commands with slightly different results:
- `INS_ETH_GET_PUBLIC_KEY` (`0xE0, 0x02, ...`): if the transport gets closed it will always freeze the app and restart the device
- `INS_ETH_SIGN` (`0xe0, 0x04, ...`): if the transport gets closed it doesn't always causes the same problem, but it will make it impossible to send new requests to the app using new transports until the user restarts the application on their device manually.

**Comment by becominginsane** [comment]
Merge fixed in dev
