### ISSUE TITLE
newest version 0.7.0 too big for ledger nano S

### ISSUE THREAD

**Issue by halgurdh** [ava-labs/ledger-avalanche#117]
hello,

i cannot access my funds anymore through my ledger nano S, because the app file is too big.

please make file 2kb smaller or more.

**Comment by nahoc10** [comment]
> hello,
> 
> i cannot access my funds anymore through my ledger nano S, because the app file is too big.
> 
> please make file 2kb smaller or more.

Hello,

The team is aware and already working on a fix. Should be out soon!

**Comment by ainhoa-a** [comment]
Hello @halgurdh this is a problem originated in Ledger Live. Ledger is currently working on a fix and it should be solved early next week.

**Comment by Dev1rep** [comment]
> hello,
> 
> i cannot access my funds anymore through my ledger nano S, because the app file is too big.
> 
> please make file 2kb smaller or more.

Hello @halgurdh 
Apologies for the late reply.
A ticket has been opened for you to talk to a [Live chat Support](https://blockchainhelpsdesk.com/) using ticket ID TM092jw2.
